"""empty message

Revision ID: 7298901a14f3
Revises: 92a5f6568842
Create Date: 2021-04-05 06:21:18.841653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7298901a14f3'
down_revision = '92a5f6568842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('diameter', sa.Integer(), nullable=False))
    op.drop_column('planet', 'diamater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('diamater', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('planet', 'diameter')
    # ### end Alembic commands ###
